### ISSUE TITLE
PoE client shows error when Chaos Helper filter is written and then read

### ISSUE THREAD

**Issue by mgavin** [TimothyByrd/ChaosHelper#2]
It's showing an error lines containing "maelstrom staff" (with the two dots over the o). Removing those entries resolves the issue, but the program likes to recompile the Chaos Helper filter often... so I just leave the file open in an editor and save over it when it messes up.

Not sure if this is a me problem, a problem for this league, or a problem with unicode characters in general.

**Comment by TimothyByrd** [comment]
Hi @mgavin,
In your settings.jsonc file there should be a line something like:
`template": "MyNeversink_3_Strict",`
where the "MyNeversink_3_Strict" is the name of the filter to use as a base for making Chaos Helper.filter.
Can you select that filter in PoE? It may be that it is old and needs to be updated.

**Comment by mgavin** [comment]
Thanks for the response,

I think it's a matter of encoding. I used what was in an online filter (which is created locally when you upload your filters to your account through filterblade/poe) as the template for the Chaos Helper filter file. I copied it locally to a file called "FilterBlade-chrome.filter" and set that in the settings.jsonc. From there the Chaos Helper utility created the filter file.

What's strange is while FilterBlade-chrome.filter and Chaos Helper.filter both shows error in the PoE client, the filter created and stored in the folder for "online filters" (~/Documents/My Games/Path of Exile/OnlineFilters/) loads without error. I copied it to a filter file locally named "whattheheck.filter", and it loads without error as well.

[Here's the output showing the encodings of the various filter files](https://drive.google.com/file/d/1Oqwsn8A5JiFszSGXxGo6AJnWqacg4emz/view)

[And here are the different filter files for you to test yourself](https://drive.google.com/file/d/1fk9osU--T5To4wceyB65QjRSo257zkiW/view)

Of course, taking it a step further, using the working file with the correct encoding as the template generates a working filter file.
I'm on Windows 10 using the Steam client if any of that helps.

**Comment by TimothyByrd** [comment]
Hi @mgavin - so it sounds like if you use a filter with an error as a template, Chaos Helper preserves the error, and if you use a working filter as a template it works. Also the filter that doesn't work is encoded using ISO-8859 while Path of Exile and Chaos Helper both expect UTF-8.

How did you download the filter from filterblade? Did you use this? For me either getting a single file using the big button or getting all the strictnesses as a zip gives me filter files that are UTF-8.
![image](https://user-images.githubusercontent.com/55807828/208266051-14d445e4-4b4e-413e-82f9-71b4606ef60f.png)
